services:
  fronius-ms:
    build: .
    image: ghcr.io/voltcast-a-ase-project/shelly-microservice/shelly-ms:latest
    networks:
      - VoltCast_Network
    ports:
      - "8083:8083"
    expose:
      - "8083"

networks:
  VoltCast_Network:
    external: true
